### ISSUE TITLE
Math rendering broken

### ISSUE THREAD

**Issue by chris-hld** [sfstoolbox/sfs-documentation#30]
Math is not rendered in http://sfstoolbox.org/en/2.9.0/

**Comment by hagenw** [comment]
Thanks, I forgot that for the v2.9 branch the doc is build for a release and not for the actual branch. I created a new release 2.9.1, which includes the desired updates to the math engine:
http://sfstoolbox.org/en/2.9.1/
This is also the new default version, where http://sfstoolbox.org is pointing to.

**Comment by chris-hld** [comment]
Thanks!
