### ISSUE TITLE
Fix summation limit N for explicit solutions

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-documentation#9]
As Till reported in his mail:

In the expansions of the basis functions [(4)](http://kkdu.org/sfs/theory/index.html#equation-G_expansion), [(5)](http://kkdu.org/sfs/theory/index.html#equation-D_expansion), [(6)](http://kkdu.org/sfs/theory/index.html#equation-S_expansion), the usage of `N` as limit of the summation is misleading as it suggests a finite number of basis functions.
The definition of a Fredholm operator states that the kernel has finite dimensions and its mapping should be infinite.

=> `N` should be infinite

**Comment by hagenw** [comment]
I have looked into  [MorseFeshbach1981] -- it should be page 940, not eq. 940! --, there the trick is that no summation limit at all is mentioned, but simply $\sum_{n}$.

Should I change it to the same, or better replace `N` by `∞` (infinity)?

A related question would be if the functions are also correct for the [planar](http://kkdu.org/sfs/theory/index.html#planar-geometries) and [linear case](http://kkdu.org/sfs/theory/index.html#linear-geometries) where we don't have a summation, but an integral as the volume is a non compact space.

**Comment by fs446** [comment]
> Should I change it to the same, or better replace N by ∞ (infinity)?

change to inf would be good and consistent with other HOA related stuff so far.

> A related question would be if the functions are also correct for the planar and linear case where we don't have a summation, but an integral as the volume is a non compact space.

Compact operators and non-compact ones such as the linear/planar deconvolution must and should be treated independently.

**Comment by ghost** [comment]
> Should I change it to the same, or better replace N by ∞ (infinity)?

Matter of taste, I guess.
Personally, I like $\sum_{n \in \mathbb{Z}}$ for the abstract case.
When working in a particular space (e.g. circular or spherical harmonics), switch to whatever indexing is convenient.

I completely agree that the planar (and linear) case should be treated independently.

**Comment by hagenw** [comment]
> > Should I change it to the same, or better replace N by ∞ (infinity)?
> 
> Matter of taste, I guess.
> Personally, I like $\sum_{n \in \mathbb{Z}}$ for the abstract case.
> When working in a particular space (e.g. circular or spherical harmonics), switch to whatever indexing is convenient.

Good point, the actual summation indices can be from 0 to \inf or from -\inf to \inf depending on the basis function, correct?
I solved the problem by using $\sum_n$ and state in the description that $n \in \mathbb{Z}$.

I also added the same three equations with \int instead of \sum for the non compact case, see:
http://kkdu.org/explicit_solution/theory/index.html#solution-for-special-geometries-nfc-hoa-and-sdm

There I'm not sure if it is ok to just write `dk` as integration index, or is there a better option. Are the integration boundaries always -\inf to \inf? At the moment I have omitted them.

**Comment by ghost** [comment]
Caveat: I'm not an expert.

> There I'm not sure if it is ok to just write dk as integration index

Probably not. In the abstract setting, we don't know where k lives. We could possibly assume a mesurable space and integrate w.r.t. the measure $\mu$.

Does the mathematical formulation for general infinite domains exist in the SFS literature?
If not then this may be a can of worms...

An option would be to ditch the abstract case altogether and adopt a more "hands-on" signal processing perspective:
Then NFCHOA and SDM are deconvolutions (inverse filtering), carried out in appropriate transform domains.

**Comment by hagenw** [comment]
I decided to go with the abstract measure $\mu$. At the moment I still prefer the mathematical approach to motivate the deconvolution. But if we find a better way, we could change it later one. For now I will close this issue.
